name: Docker Image CI

on:
  push:
    branches: [ "PROD" ]
  pull_request:
    branches: [ "PROD" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build frontend image
        run: docker image build -t image
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
